# Generated by Django 4.0.5 on 2022-06-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code1_text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Code2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code2_text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_int', models.IntegerField(default=0)),
            ],
        ),
    ]
